### ISSUE TITLE
Do fizzbuzz

### ISSUE THREAD

**Issue by misolove** [misolove/gh-flow-practice#2]
## Tasks

- [ ] Print fizz, if i is multiple of 3.
- [ ] Print buzz, if i is multiple of 5.
- [ ] Print fizzbuzz, if i is multiple of 15.
- [ ] Otherwise, print i itself

## Reference

- [Fizzbuzz wikipedia](https://www.goole.com)
